### ISSUE TITLE
asignación 2

### ISSUE THREAD

**Issue by geora2518** [maestria-geotel-201902/unidad-0-asignacion-2-preguntas-investigacion-geora2518#1]
@geofis. terminada la asignación, no estaba segura de ponerle los signos de interrogación a las preguntas. ¿ las mayúsculas se toman en cuenta en la plataforma?

**Comment by geofis** [comment]
@geora2518 En aras de que se vean como preguntas, pues sí que es deseable colocar los signos de interrogación. Y sí, es posible usar mayúsculas, dado que Markdown las interpreta adecuadamente. En todo caso, cuando hagas tus cambios en GitHub, si quieres ver cómo quedaría tu documento, puedes usar la pestaña `Preview`

**Comment by geora2518** [comment]
@geofis He recibido el correo y estoy  de acuerdo con lo sugerido, los datos que me encontré en la ONE solo me sumista el dato por año y municipio de los desechos depositados en el Gran Santo Domingo, pero, me gusta la idea de relacionar con la variable de hacinamiento y otras, estaré buscando datos a ver que puedo obtener. Muchas gracias por las sugerencias. Tali jjjjj

**Comment by geofis** [comment]
Perfecto. Si hay datos que permitan estimar el grado de hacinamiento (quizá el censo tiene algo al respecto, o quizá por medio de la boleta para evaluación los riesgos), entonces sí que es posible utilizarlo. Cuando tengas las preguntas nuevamente redactadas/revisadas, me puedes notificar haciendo mención en un comentario del último *commit* que hagas.

Fdo. El tali.
