### ISSUE TITLE
Cargar datos

### ISSUE THREAD

**Issue by geora2518** [maestria-geotel-201902/unidad-0-asignacion-2-preguntas-investigacion-geora2518#2]
¿como puedo cargar los archivos, los tengo descargados en Excel, desde la pagina de la ONE y el censo  2010?

**Comment by geofis** [comment]
Por medio del botón `Upload files`

![image](https://user-images.githubusercontent.com/13460617/67153436-0185e580-f2b7-11e9-97c8-7f1079987a39.png)
